### ISSUE TITLE
Why are timesteps a power of 2?

### ISSUE THREAD

**Issue by jimouris** [elibensasson/libSTARK#23]
I am reading the [whitepaper](https://eprint.iacr.org/2018/046.pdf) and I am trying to understand why in this implementation the timesteps (`-t` flag) should be declared as a power of 2.

In the paper, if I haven't missed anything, no such thing is mentioned.
> "α is the result of executing C for T steps on (public) input x"

Thanks,
Dimitris Mouris

**Comment by elistark** [comment]
Good question: the STARK paper does use powers of 2, see, e.g.,
Definition B.5 there (T=2^t-1).
Why? Because succinctness: if you want verifier to be able to argue
*algebraically* about long computations, it's better to use evaluation
domains that are elements of a (coset) of some group that is
"FFT-friendly". It can be a multiplicative group of size 2^k, integer k (as
is often done when working with SNARKs) and it can be an additive group, as
used in the STARK paper you refer to.

Best
Eli

**Comment by jimouris** [comment]
Got it, thank you!
